### ISSUE TITLE
Perfomance issue

### ISSUE THREAD

**Issue by Lev1t** [Drizin/DapperQueryBuilder#26]
Hello everyone. Thanks for your work.
This is my first issue, so don't get me wrong. 
I'm in love with fluent code style, but i've a huge perfomance issue using the DapperQueryBuilder.
TLDR: ~6k ms overhead for querying using this library. 
Am I doing somthing wrong?
UPD: Sorry, I've found that it is a Dapper parameterized query problem

```
            var stopWatch = new Stopwatch();
            stopWatch.Start();
            var fluentSingle = await DbConnection.FluentQueryBuilder()
                .Select($"*").From($"api.vwReserves").Where($"Id = {reserveId}").QuerySingleAsync<vwReserve>();
            stopWatch.Stop();
            var fluentSingleElapsed = stopWatch.ElapsedMilliseconds; //~6k ms

            stopWatch.Reset();
            stopWatch.Start();
            var simpleBuilder = await DbConnection.QueryBuilder($@"SELECT * FROM api.vwReserves WHERE Id = {reserveId}")
                .QuerySingleAsync<vwReserve>();
            stopWatch.Stop();
            var simpleBuilderElapsed = stopWatch.ElapsedMilliseconds; //~6k ms

            stopWatch.Reset();
            stopWatch.Start();
            var dapperQuery = await DbConnection.QuerySingleAsync<vwReserve>($"SELECT * FROM api.vwReserves WHERE Id = {reserveId}");
            stopWatch.Stop();
            var dapperElapsed = stopWatch.ElapsedMilliseconds; // ~15ms
```

**Comment by Drizin** [comment]
Can you elaborate? I'm very curious about what was happening.

**Comment by Lev1t** [comment]
> Can you elaborate? I'm very curious about what was happening.

I'm working with Sql Server on my current project. It has the parameter_sniffing option which is enabled by default. Stored procedures execution plans caches on the first execution using plan for specific parameters. This plan might be suboptimal for another parameters. In our case following sql will be generated using dapper query with parameters:
```exec sp_executesql N'SELECT * FROM api.vwReserves WHERE Id = @p0',N'@p0 int',@p0=42```
I don't know why the problem appears in case of sp_executesql for the specific query, because for another queries all works fine. 

The view api.vwReserves used in the query is pretty complicated: many joins, window functions (like OVER(PARTITION BY)).

Maybe I need to rewrite the query a bit or somehow clear cache.

If append query with OPTION(RECOMPILE) then sql server will generate new execution plan so the problem will disappear.
```SELECT * FROM api.vwReserves WHERE Id = @p0 OPTION(RECOMPILE)```
or
```EXEC sp_executesql '...' WITH RECOMPILE```
may be I should include this hack into the view.

**Comment by Drizin** [comment]
I see. I am familiar with cached execution plans (and bad caching strategies), but I was puzzled about how you could get bad timings in two consecutive tests and then better timings when using pure dapper **with the same id**.

But I think I understood it now: your last query is not using parametrized values - you're passing a raw string (dynamic SQL), so SQL is forced to reevaluate the execution plan. Probably you had a cached execution plan which was good for some other values but not for your `reserveId`. With parametrized values you'd get the bad plan, while with dynamic SQL the server would evaluate a new plan.

Thanks for sharing!
