### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by davidbuckleyni** [Drizin/DapperQueryBuilder#29]
Why on earth would u do this this is just as bad as string.format interpulation is open to sql inejection

**Comment by Drizin** [comment]
@davidbuckleyni have you read the documentation? Right in the first paragraphs you'll see that the library DOESN'T use plain string interpolation, and is NOT vulnerable to sql injection.
You can check out the source code to see how it works. 
If you can make sql injection with the library please share your code.

**Comment by Drizin** [comment]
Entity Framework also does the same trick when using [`FromSqlInterpolated()`](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql), and this is also parametrized (injection-safe).
