### ISSUE TITLE
Support for MySql, Sqlite , and Oracle

### ISSUE THREAD

**Issue by aboah** [Drizin/DapperQueryBuilder#33]
Please some of us would be glad to know whether your package (Dapper Query Builder)  supports for MySql, Sqlite , and Oracle.
These flavors of sql have slight changes in query formation.

**Comment by Drizin** [comment]
@aboah please check the [Database Support](https://github.com/Drizin/DapperQueryBuilder#database-support) part. To sum, the main library is database agnostic, and the only generated statements are `WHERE`, `AND`, `OR`, which as far as I understand is just SQL ANSI and should work with all vendors. 
Do you have any specific issue that is not working with some database?
