### ISSUE TITLE
PascalCase for a table name?

### ISSUE THREAD

**Issue by dbjina** [Drizin/DapperQueryBuilder#34]
I use a postgres database.
I tried the below code. It did not work.

var schema = "sample";
var table = "Test2";
var sql = connection.CommandBuilder($@"
                INSERT INTO {schema:raw}.{table:raw} (name)
                VALUES ({test_name})
            ";

The error message was relation "sample.test2" does not exist

Does it not support any capital letters for a table name?

**Comment by Drizin** [comment]
I don't think DapperQueryBuilder does anything regard casing. As far as I understand PostgreSQL will automatically lowercase schemas, table names, column names, etc. Unless you quote them.
Please check: https://stackoverflow.com/questions/20878932/are-postgresql-column-names-case-sensitive

You can try double quotes or quotes outside the interpolated values:

```
var schema = "sample";
var table = "\"Test2\"";
var sql = connection.CommandBuilder($@"
INSERT INTO {schema:raw}.{table:raw} (name)
VALUES ({test_name})
";
```

or 

```
var schema = "sample";
var table = "Test2";
var sql = connection.CommandBuilder($@"
INSERT INTO {schema:raw}."{table:raw}" (name)
VALUES ({test_name})
";
```

**Comment by Drizin** [comment]
@dbjina - did it work?
