### ISSUE TITLE
Missing parentheses in example

### ISSUE THREAD

**Issue by miroslavp** [Drizin/DapperQueryBuilder#38]
In your example below there are missing parentheses at the end before semicolon

string productName = "%Computer%";
int subCategoryId = 10;

var products = cn
    .QueryBuilder($@"
    SELECT * FROM Product
    WHERE
    Name LIKE {productName}
    AND ProductSubcategoryID = {subCategoryId}
    ORDER BY ProductId"
    ).Query<Product>;

**Comment by Drizin** [comment]
Thanks for pointing that out. Fixed.
