### ISSUE TITLE
string interpolation during instantiation isn't working.

### ISSUE THREAD

**Issue by matt14m** [Drizin/DapperQueryBuilder#4]
Hi there,
I have a situation where I have dynamic tables / views that share the same structure. For this reason I need to dynamically name the table. When I instantiate the querybuilder as seen below the "{sessionId}" gets translated to "@p0"

var qry = conn.QueryBuilder($@"select * from d_common.TrackData_{sessionId}_v where 1=1");

It appears that the parameter part of the Formattablestring is not making it to the query.

This line:
var results = qry.Query<TrackData>().ToList();
Yields:
"42601: syntax error at or near \"@\""

qry.sql = "select * from d_common.TrackData_@p0_v where 1=1"
qry.parameters does include my sessionId

Am I using it wrong or is this a bug?

**Comment by Drizin** [comment]
Hi @matt14m ,
If you want the interpolated blocks to remain as strings (and not be converted to sql parameters) you can use the "raw" modifier (see the documentation). Like this:

`var qry = conn.QueryBuilder($@"select * from d_common.TrackData_{sessionId:raw}_v where 1=1");`
