### ISSUE TITLE
[comment/kudos] this is amazing.

### ISSUE THREAD

**Issue by jeremysimmons** [Drizin/DapperQueryBuilder#47]
Not sure exactly how many goats were sacrificed in the building of this library, but just wow. 
Thanks so much for writing it. I learned about how a $"" is actually an instance of FormattableString. Amazing.

**Comment by Drizin** [comment]
Hi @jeremysimmons - honestly I've sacrificed a few nights and weekends, but the good part is that I've also learned a ton with this project.
Thanks for your kind words - it really made my day. :blush:
