### ISSUE TITLE
Use QueryBuilder Multiple Times

### ISSUE THREAD

**Issue by terryaney** [Drizin/DapperQueryBuilder#5]
Is it possible to use a qb multiple times?

```
var qb = cn.QueryBuilder( $"SELECT * FROM Foo /**where**/" );

var fileKey = 12;
var files = qb.Where( $"Bar = {fileKey}" ).QueryAsync<ListFile>();

fileKey = 13
files = qb.Where( $"Bar = {fileKey}" ).QueryAsync<ListFile>();
```

Very simply query, but if I have a complex query and I don't want to write it twice.  Obviously, I could break it out into separate method, but wondering if something like this is possible all within one method?

**Comment by Drizin** [comment]
Cleaning up previous filters would require QueryBuilder to expose some internal fields (_commandBuilder.Parameters and _filters).

I think the best option is really creating a reusable method to reuse your initial query. QueryBuilder is a very lightweight wrapper, so it shouldn't be a problem.
