### ISSUE TITLE
Bulk insert list of objects

### ISSUE THREAD

**Issue by h3rkO** [Drizin/DapperQueryBuilder#50]
Hello, 
When im using dapper with the following query:
```

DECLARE @TempTable TABLE(
ID int not null,
Name nvarchar(255) not null
)

INSERT INTO @TempTable VALUES (@ID, @Name)
```

and c# code 
```
public class TestClass
{
    public int ID { get; set; }
    public string Name { get; set; }
}

var params = new List<TestClass>(); // add objects


using Dapper;
 ... conn.Execute(sql, params)

```
dapper manages to resolve list and insert all objects into the temp table.
Now i'm trying to use feature of QueryBuilder with this approach but without success.
Any advise how can use list insert with QueryBuilder ? 

Thanks,
Nikolay.

**Comment by Drizin** [comment]
What would be the advantage of using DapperQueryBuilder in this scenario?
I don't see how it would be any better than pure Dapper.
