### ISSUE TITLE
Automatic reuse of duplicated parameters

### ISSUE THREAD

**Issue by aleksei-oecd** [Drizin/DapperQueryBuilder#51]
Is reuse of dubplicated parameters broken ? The code from manual 

```csharp
string productName = "Computer";
var query = conn.QueryBuilder($"SELECT * FROM Product WHERE Name = {productName} OR Category = {productName}");
```
generates following sql:

```sql
SELECT * FROM Product WHERE Name = @p0 OR Category = @p1
```

**Comment by Drizin** [comment]
Try setting [DapperQueryBuilderOptions.ReuseIdenticalParameters](https://github.com/Drizin/DapperQueryBuilder/blob/master/src/DapperQueryBuilder/DapperQueryBuilderOptions.cs#L36) to true
