### ISSUE TITLE
[Question] FluentQueryBuilder: How to pass TableName dynamically?

### ISSUE THREAD

**Issue by bokidotnet** [Drizin/DapperQueryBuilder#52]
Found issues for From method as follow:

`

        Dim q As FluentQueryBuilder = DbConnection.FluentQueryBuilder()
        Dim ProductId As Integer = 1
        Dim TableName As String = "products"

        With q
            .Select($"ProductId")
            .Select($"ProductName")
            .From($"{TableName}")
            .Where($"ProductId = {ProductId}")
            .OrderBy($"ProductName")
        End With

        Debug.WriteLine(q.Sql)

        Dim p As List(Of Product) = q.Query(Of Product)()
`

Result:
SELECT ProductId, ProductName
FROM @p0
WHERE ProductId = @p1
ORDER BY ProductName

**If I set fixed string values then everything is working well.**

`

        Dim q As FluentQueryBuilder = DbConnection.FluentQueryBuilder()

        With q
            .Select($"ProductId")
            .Select($"ProductName")
            .From($"Products")
            .Where($"ProductId = 1")
            .OrderBy($"ProductName")
        End With

        Debug.WriteLine(q.Sql)

        Dim p As List(Of Product) = q.Query(Of Product)()
`

Result:
SELECT ProductId, ProductName
FROM Products
WHERE ProductId = 1
ORDER BY ProductName

Also If I set fixed string value of table name and use where part as dynamic value then also is working.

`

        Dim q As FluentQueryBuilder = DbConnection.FluentQueryBuilder()
        Dim ProductId As String = 1

        With q
            .Select($"ProductId")
            .Select($"ProductName")
            .From($"Products")
            .Where($"ProductId = {ProductId}")
            .OrderBy($"ProductName")
        End With

        Debug.WriteLine(q.Sql)

        Dim p As List(Of Product) = q.Query(Of Product)()
`

Result:
SELECT ProductId, ProductName
FROM Products
WHERE ProductId = @p0
ORDER BY ProductName

Guess only issue is From method if you want to use it for table soruce.

**Comment by Drizin** [comment]
Use the [raw modifier](https://github.com/Drizin/DapperQueryBuilder#raw-modifier-dynamic-table-names), like this:
```cs
        .From($"{TableName:raw}")
```

**Comment by bokidotnet** [comment]
> 

Thanks mate!

I followed documentation and didn't noticed that as any option :)
It would be a nice to include this kind of example as well in documenation for other people.

Anyway, shell I use :raw sufix and for other methods or this is only for From() method?

**Comment by Drizin** [comment]
Only for things that you do NOT want to be parameterized. 
Anything that you pass with this modifier should be safe (you probably don't want to allow user-input here)

**Comment by bokidotnet** [comment]
Of course. Idea  was for internal code part and code resuse to keep it 'dry'.
