### ISSUE TITLE
AppendLine too slow when AppendLine 8000 more  line 

### ISSUE THREAD

**Issue by Broderick890** [Drizin/DapperQueryBuilder#53]
Hi there! Thank your library! But AppendLine too slow  when AppendLine 8000 more  lines .Each appended script line was very simple. Scipt line like this: insert into (A,B) select {var1:raw},{var2:raw}.It take about 30 seconds

**Comment by Drizin** [comment]
Appending new string blocks is a little slow and certainly could be improved.

Having said that, this library doesn't seem to be the right tool for what you're doing. I suggest that you try using pure Dapper. Search for bulk-inserts using Dapper.
