### ISSUE TITLE
Support Filters initializer with IFilter arguments

### ISSUE THREAD

**Issue by LarsStegman** [Drizin/DapperQueryBuilder#57]
I have a class `Source` that contains a field `IDictionary<string, string> Tags`. I want to create Filters based on these tags. I would like to be able to initialize the filter like this:

```
new Filters(Filters.FiltersType.OR, source.Tags.Select(t =>
        new Filters(Filters.FiltersType.AND)
        {
            new Filter($"TAGS.[Key] = {t.Key}"),
            new Filter($"TAGS.Value = {t.Value}")
        }
    )
);
```

This requires a new initializer on Filters:

```
public Filters(FiltersType type, IEnumerable<IFilter> filters);
```

The `public Filters(FiltersType type, params FormattableString[] filters)` initializer can then just call the new one.

**Comment by Drizin** [comment]
Sounds like a good idea. Would you like to create a PR for this?

**Comment by Drizin** [comment]
Thank you for the PR!
