### ISSUE TITLE
Duplicate Parameters

### ISSUE THREAD

**Issue by terryaney** [Drizin/DapperQueryBuilder#6]
Wondering if there would be a way for you to detect if params in a query/interpolated string are identical and if so, don't add another param with duplicated value, but use the previously created parameter's name?

![image](https://user-images.githubusercontent.com/6237247/107294173-9378ab00-6a32-11eb-9d69-9cc140db0a6b.png)

In above case, 3 `null` parameters could be reduced to one (I think, maybe has to be conditional on type?), 3 `dates` down to 1, 2 'string dates' down to one and two 'terry.aney' params down to one.  So 12 parameters instead of 18 in this case.

I had written a query building library for another project that did something similar and it allowed a major reduction in parameters.  Although, that library was building extremely large queries in a `StringBuilder` and appending queries over and over, so hundreds of parameters.  So with the way QueryBuilder is built, not exactly the same scenario (unless you allow for an AppendQuery at some point).  Thought I would mention it in case it was an easy change.

**Comment by Drizin** [comment]
Looks like this is not working fully. See my unit test and my comments in PR https://github.com/Drizin/DapperQueryBuilder/pull/8/

**Comment by Drizin** [comment]
Actually I think I've fixed now (it was a problem with object comparisons).
Can you please check if it's working fine?

**Comment by terryaney** [comment]
Seems to be working in my few tests.
