### ISSUE TITLE
HELP: Error 'ICompleteBuilder<IFluentQueryBuilder, SqlBuilder, IDapperSqlCommand>' does not contain a definition for 'Query'

### ISSUE THREAD

**Issue by tharlab** [Drizin/DapperQueryBuilder#66]
`Error (active)	CS1929	'ICompleteBuilder<IFluentQueryBuilder, SqlBuilder, IDapperSqlCommand>' does not contain a definition for 'Query' and the best extension method overload 'IDapperSqlBuilderExtensions.Query(IDapperSqlBuilder, IDbTransaction?, bool, int?, CommandType?)' requires a receiver of type 'InterpolatedSql.Dapper.SqlBuilders.IDapperSqlBuilder'	242`

my query is:
`con.FluentQueryBuilder().Select(......).Query();`

Error only happen when i am using v2.0.0 stable release,
and it work well when i am using v2.0.0-beta2 or beta1
my project is blazor dotnet 8 webapp

**Comment by Drizin** [comment]
Try `.Build().Query()`

**Comment by tharlab** [comment]
> Try `.Build().Query()`

many thanks save me, it work,
now i can update to stable release.....
