### ISSUE TITLE
AppendLine doesn't appear to be working

### ISSUE THREAD

**Issue by terryaney** [Drizin/DapperQueryBuilder#7]
```
var qb = cn.QueryBuilder( $@"
INSERT[ Log ]( Action, FolderName, FileName, VersionID, VersionIndex, [User], Size )
SELECT 'D', fo.[Name], fi.[Name], ve.VersionID, ve.VersionIndex, {user}, ve.Size
FROM Version ve 
	INNER JOIN [File] fi ON fi.UID = ve.[File] 
	INNER JOIN Folder fo ON fo.UID = fi.Folder 
WHERE ve.[File] = {parameters.Id}" );

if ( parameters.Soft )
{
	qb.AppendLine( $"UPDATE [File] SET Deleted = 1 WHERE UID = {parameters.Id}" );
}
else
{
	qb.AppendLine( $"UPDATE [File] SET Deleted = 1 WHERE UID = {parameters.Id}" );
}
```

Given the code above, I should have one INSERT into Log table and one UPDATE on File table.  But if I stop on a breakpoint and look at `qb.Sql`, I see the following (note that `Parameters` appears to be correct):

![image](https://user-images.githubusercontent.com/6237247/107320277-018a9580-6a66-11eb-865b-79e421556aca.png)

**Comment by SimonCapewell** [comment]
I've just noticed this too. Seems to be working on the master branch though. Looks like it's fixed by this commit, but not released yet https://github.com/Drizin/DapperQueryBuilder/commit/4bd87e343723b20b56d61ddf41975f17f60b5447

**Comment by terryaney** [comment]
@SimonCapewell Regrettably, I'm just 'now' getting into using/integrating OSS nuget libraries into my projects.  What is standard practice here?  Pull repo, build it, and reference it, and remove nuget package reference in my project?  Then reverse all that when updated package comes out?  Is there something clever built into VS to make this easier or no?

**Comment by Drizin** [comment]
I've just published a new nuget package Dapper-QueryBuilder 1.0.6 with latest fixes. 

This specific problem (`.Append()` and `.AppendLine()` were not playing well with `.Where` filters from `QueryBuilder`) was reported to me in a private email (late December), and I was still waiting for the reporting user to confirm if it was fixed.

Thanks for reporting. Please update the package and let me know if the new package works fine now.

**Comment by terryaney** [comment]
Yep, seems to work now.

**Comment by Drizin** [comment]
Great.
BTW, that's was a nice example of issuing multiple statements in a single batch. Thanks for sharing.

**Comment by terryaney** [comment]
Unfortunately, found a problem...

```
var qb = cn.QueryBuilder( $@"
{FileInfoSelect( null ):raw}

FROM [File] f
	INNER JOIN Folder fo ON f.Folder = fo.UID
	CROSS APPLY (
		SELECT TOP 1 v.UploadedBy, v.Time, v.Size, v.ContentType, v.VersionID, v.UID
		FROM Version AS v
		WHERE v.[File] = f.UID AND ( {version} = '' OR v.VersionID = {version} )
		ORDER BY v.Time DESC
	) v" );

qb.AppendLine( @$"
WHERE fo.Name = {parameters.Folder}

ORDER BY f.Name
OFFSET {parameters.PerPage * ( parameters.Page - 1 )} ROWS
FETCH NEXT {parameters.PerPage} ROWS ONLY" );
```

`FileInfoSelect` simply generates a select list that is shared across several diff query builders, but the resulting SQL from this is:

```
SELECT
	f.UID Id, 
	fo.Name FolderName, 
	f.Name Name, 
	f.Description Description,
	v.VersionID Version, 
	v.ContentType ContentType, 
	v.UploadedBy UploadedBy, 
	f.CheckedOutBy CheckedOutBy, 
	v.Time UploadTime, 
	v.Size Size,
	v.UID Token

FROM [File] f
	INNER JOIN Folder fo ON f.Folder = fo.UID
	CROSS APPLY (
		SELECT TOP 1 v.UploadedBy, v.Time, v.Size, v.ContentType, v.VersionID, v.UID
		FROM Version AS v
		WHERE v.[File] = f.UID AND ( @p0 IS NULL OR v.VersionID = @p1 )
		ORDER BY v.Time DESC
	) v
WHERE fo.Name = @p4

ORDER BY f.Name
OFFSET @p3 ROWS
FETCH NEXT @p4 ROWS ONLY
```

And the parameters are:

![image](https://user-images.githubusercontent.com/6237247/107548213-fb92d280-6b93-11eb-8401-7833c2bcd341.png)

Somehow, `fo.Name = @p4` is incorrectly set to `@p4` instead of `@p2`.

**Comment by Drizin** [comment]
@terryaney Thanks for reporting. I think I could fix it in a safer way, using regex to match all parameters and replacing all at once (without having to use string tricks). 
Can you please check if it works for you? I added a unit test (no SQL required) which was failing and now works.
Thanks!

**Comment by terryaney** [comment]
Yep, this is working as well.  Regex is nuts!  Glad you can read/write it ;)

**Comment by Drizin** [comment]
Turns out what I wrote was broken, as reported in https://github.com/Drizin/DapperQueryBuilder/issues/19 
I'm publishing a new fix, but to be on the safe-side I've set this ["reuse existing parameters"](https://github.com/Drizin/DapperQueryBuilder/pull/8) to be experimental (disabled by default).

**Comment by terryaney** [comment]
How do you enable the feature?

On May 1, 2021 at 11:41 AM, Rick Drizin ***@***.***> wrote:






Turns out what I wrote was broken, as reported in #19
I'm publishing a new fix, but to be on the safe-side I've set this "reuse existing parameters" to be experimental (disabled by default).

**Comment by Drizin** [comment]
@terryaney - global variable `DapperQueryBuilderOptions.ReuseIdenticalParameters = true`

**Comment by Drizin** [comment]
@terryaney BTW - I saw your tweet about multi-line queries being realigned (trimmed) - would you like to open an issue for that?

**Comment by terryaney** [comment]
> @terryaney - global variable `DapperQueryBuilderOptions.ReuseIdenticalParameters = true`

Where's the best place to put this in an asp.net core web api?

**Comment by terryaney** [comment]
> @terryaney BTW - I saw your tweet about multi-line queries being realigned (trimmed) - would you like to open an issue for that?

I should probably know what this is, but I can't remember, and I was trying to clean up my to do list (emails), but I can't find a tweet from me around this time.  

a) Can you find the tweet?
b) Is this still an issue or did you resolve it?
